---
#
# Installing Kibana
#

# Add key for kibana repo
#- name: Import a key for kibana rep1
#  ansible.builtin.apt_key:
#    state: present
#    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Import a key for kibana rep2
  ansible.builtin.apt_key:
    state: present
    url: http://elasticrepo.serveradmin.ru/elastic.asc

# Add kiban repos
#- name: Add kibana rep1
#  ansible.builtin.apt_repository:
#    repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
#    state: present
#    filename: elastic-8.x

- name: Add kibana rep2
  ansible.builtin.apt_repository:
    repo: deb http://elasticrepo.serveradmin.ru bullseye main
    state: present
    filename: elasticrepo

# Install Kibana 

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.hosts:'
   line: 'elasticsearch.hosts: ["http://{{ elkserver_ip }}:9200"]'

# Starting Kibana

- name: Starting kibana
  service:
   name: kibana
   state: started
   enabled: true
   daemon-reload: yes
