---
#
# Playbook to install fail2ban and ufw
#
- hosts: bast1
  become: yes
  become_user: root
  roles:
  - { role: ufw }
  - { role: ufw-zabbix-agent }
  - { role: fail2ban }

- hosts: elk1
  become: yes
  become_user: root
  roles:
  - { role: ufw-elk }
  - { role: ufw-zabbix-agent }
  - { role: fail2ban }


- hosts: webservers
  become: yes
  become_user: root
  roles:
  - { role: ufw-lamp }
  - { role: ufw-zabbix-agent }
  - { role: fail2ban }


- hosts: zab1
  become: yes
  become_user: root
  roles:
  - { role: ufw-zabbix }
  - { role: ufw-zabbix-agent }
  - { role: fail2ban }


- hosts: kib1
  become: yes
  become_user: root
  roles:
  - { role: ufw-kibana }
  - { role: ufw-zabbix-agent }
  - { role: fail2ban }


