---
  # UFW Configurat

- name: Install UFW firewall
  apt: name=ufw update_cache=yes state=latest

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: "UFW - Allow port 10050"
  ufw:
    rule: allow
    port: "10050"
    
- name: "UFW - Allow port 10051"
  ufw:
    rule: allow
    port: "10051"
    
- name: "UFW - Allow port 10052"
  ufw:
    rule: allow
    port: "10052"
    
- name: "UFW - Allow port 10053"
  ufw:
    rule: allow
    port: "10053"
    
