---
#
# Installing Filebeat
#

# Install gpg

- name: Install gnupg with apt
  apt:
   name: gnupg
   update_cache: yes




# Install Filebeat 

- name: install filebeat 7 from a .deb on the internet
  apt:
    deb: https://mirrors.cloud.tencent.com/elasticstack/apt/7.x/pool/main/f/filebeat/filebeat-7.17.13-amd64.deb
    state: present
  become: true
  register: apt_output

 
# Replace Filebeat configuration to ship to Logz.io. 

- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
   enabled: true
   daemon-reload: yes
