---
#
# Installing Filebeat
#

# Install gpg

- name: Install gnupg with apt
  apt:
   name: gnupg
   update_cache: yes


# Download SSL certificate:

- name: Download certificate
  shell: wget https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
  
# Create directory for certification

- name: Make new directory for cert
  shell: mkdir -p /etc/pki/tls/certs
  
# Move cert to directory

- name: Move SSL certification to new folder
  shell: cp COMODORSADomainValidationSecureServerCA.crt /etc/pki/tls/certs/


- name: Import a key for alternative repository
  ansible.builtin.apt_key:
    state: present
    url: http://elasticrepo.serveradmin.ru/elastic.asc

- name: Add alternative repository
  ansible.builtin.apt_repository:
    repo: deb http://elasticrepo.serveradmin.ru bullseye main
    state: present
    filename: elasticrepo



# Install Filebeat 

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes
 
# Replace Filebeat configuration to ship to Logz.io. 

- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
   enabled: true
   daemon-reload: yes
